name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allow-sudo: false
          allowed-endpoints: >
            _http._tcp.azure.archive.ubuntu.com:443
            _https._tcp.esm.ubuntu.com:443
            _https._tcp.motd.ubuntu.com:443
            _https._tcp.packages.microsoft.com:443
            _https._tcp.ppa.launchpadcontent.net:443
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@3d3495a8edde019283ece78087c4da133d03dd57 # v2.1.16
      - uses: fish-shop/indent-check@db90fa808dfeb434620e553dec75ba0967a557e8 # v2.2.107
      - uses: fish-shop/syntax-check@f74533521a177bc1047ea185e97dce5e89a643bd # v2.2.105
      - uses: fish-shop/install-plugin@806063062927836938c02961c86c4aef0c760f3d # v2.3.109
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@c23b1de96c5ad65f8601d4030f8d2b2200e23a5d # v2.3.109
