name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

jobs:
  check-fish:
    uses: halostatue/halostatue/.github/workflows/fish-tests.yml@6cc8904b869c62229f9338c4fd75beeda12174ae # v1.1.0
    permissions:
      contents: read
