name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    uses: halostatue/halostatue/.github/workflows/zizmor.yml@6cc8904b869c62229f9338c4fd75beeda12174ae # v1.1.0
    permissions:
      security-events: write
      contents: read
      actions: read
